### ISSUE TITLE
Clickonce IsFileGroupDownloaded bug

### ISSUE THREAD

**Issue by dqwork** [dotnet/deployment-tools#109]
### Description

We have a filegroup in our clickonce deployment that is optional, contained in the file group are some dll's that are not directly referenced by our project and rarely get updated, they are copied into our projects output folder via a nuget package that just injects content files.

* Downloading the filegroup when needed works great.
* Future runs of that application version also works great, IsFileGroupDownloaded returns true.
* However when we updated our application but did not change any files in the file group IsFileGroupDownloaded returns false and it redownloads them.

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.deployment.application.applicationdeployment.isfilegroupdownloaded?view=netframework-4.6.2) says this:

> If a new version of the application has been installed, and the new version has not added, removed, or altered files in the file group, IsFileGroupDownloaded(String) returns true.

However this does not appear to be the case. I did a diff against both version's manifest - the only changes were the application version and the digest of our core application dll (this is what I updated).

Why then, does it say that the file group is not downloaded?

### Configuration

.NET Framework 4.6.2
Windows 10 x64
Clickonce application 

### Regression?

Given that a very similar question was asked before and never answered from 2008 https://social.msdn.microsoft.com/Forums/en-US/910e76ce-d1a2-478c-8f3d-80d736ccb7a6/isfilegroupdownloaded-bug?forum=winformssetup I would make an educated guess that this isn't something new.

**Comment by NikolaMilosavljevic** [comment]
This seems to be an issue with .NET FX Mage tool, installed with Visual Studio or .NET FX SDK. The following page describes ways to submit feedback and open issues with these products: https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019
