### ISSUE TITLE
Upgrade repo dependencies to .NET 6.0 and create a DARC subscription

### ISSUE THREAD

**Issue by lbussell** [dotnet/deployment-tools#134]
Microsoft.Deployment.DotNet.Releases needs to be included in source-build for 6.0. This repo still depends on dotnet version 5.0.0-beta.21064.2 (see eng/Version.Details.xml), but needs to be upgraded to 6.0 so that we can use our source-build intermediate packages to build dotnet_releases from this repo.

A darc subscription should also be set up so this repo can be automatically kept up to date. This looks like the right documentation for that: <https://github.com/dotnet/arcade/blob/main/Documentation/DependencyFlowOnboarding.md>

**Comment by NikolaMilosavljevic** [comment]
This was completed.
