### ISSUE TITLE
Internal CI is broken

### ISSUE THREAD

**Issue by lbussell** [dotnet/deployment-tools#142]
It looks like this repo is failing to publish internal packages with the following error:

```
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21451.1\tools\SdkTasks\PublishArtifactsInManifest.proj(123,5): error : Package 'Microsoft.Deployment.DotNet.Releases' has stable version '1.0.247101' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
```

https://dnceng.visualstudio.com/internal/_build?definitionId=877
(internal Microsoft link)

**Comment by lbussell** [comment]
The first time this failure is recorded happened after this pull request: https://github.com/dotnet/deployment-tools/pull/133

**Comment by joeloff** [comment]
I'll revert this back to unstable until we can figure this out. I'll ping eng folks as well to see if there are other options to explore.

**Comment by lbussell** [comment]
It looks like CI is now failing on a different issue, possibly related to an expired certificate:
https://dnceng.visualstudio.com/internal/_build/results?buildId=1381379&view=logs&j=13abda86-2028-5de5-3254-ca63f887785e&t=9fe76824-2ec2-549a-7a79-2ac093d21186 (internal link)

**Comment by NikolaMilosavljevic** [comment]
This does not repro anymore.
