### ISSUE TITLE
Publish Wizard minor issue

### ISSUE THREAD

**Issue by simmotech** [dotnet/deployment-tools#161]
If you click on the groups on the left (PublishLocation, Install Location, Settings, Sign manifests, Configuration) then they are selected but the page doesn't update on the right.
If groups can be selected in any order then the click (or double-click) on the group should select it and its page.
If groups cannot be selected in any order then the clicks/highlighting should be ignored.

**Comment by NikolaMilosavljevic** [comment]
This is a feature of Visual Studio - best option to submit feedback is directly from VS: `Help` -> `Send Feedback` -> `Report a Problem` (or `Suggest a Feature`)
