### ISSUE TITLE
Publish Wizard Install Location issue

### ISSUE THREAD

**Issue by simmotech** [dotnet/deployment-tools#162]
If you use Browse to choose a local path, e.g. F:\Scratch\ClickOnceSourceTest\ then it doesn't get converted for the UNC path textbox.

Also is "file:\\\\f\Scratch\ClickOnceSourceTest\" a correct conversion for the above path?
It allows me to install the clickonce app no problem but I am seeing no updates either with Update Location set blank or set to "file:\\\\f\Scratch\ClickOnceSourceTest\".

**Comment by NikolaMilosavljevic** [comment]
This is a feature of Visual Studio - best option to submit feedback is directly from VS: `Help` -> `Send Feedback` -> `Report a Problem` (or `Suggest a Feature`)
