### ISSUE TITLE
Publish Wizard Inconsistent Line Endings

### ISSUE THREAD

**Issue by simmotech** [dotnet/deployment-tools#163]
Every time I run the Publish Wizard, VS shows the above message.for ClickOnceProfile.pubxml.user (twice actually)

**Comment by NikolaMilosavljevic** [comment]
This is a feature of Visual Studio - best option to submit feedback is directly from VS: `Help` -> `Send Feedback` -> `Report a Problem` (or `Suggest a Feature`)
