### ISSUE TITLE
Update Available Form

### ISSUE THREAD

**Issue by simmotech** [dotnet/deployment-tools#164]
A couple of old chestnuts but I thought I'd bring them up again since I feel sure that all the outstanding .NET 6 ClickOnce issues are being hard-worked upon and a glorious update release is imminent. :-)

The Update Available form looks like this:
<img width="441" alt="Snag_1e499f10" src="https://user-images.githubusercontent.com/876369/142189178-968ac19e-2367-477c-9ef6-72e805981a6e.png">

Problems are:

- No version information shown - neither current version nor new version.
It would be helpful to include this for support purposes
- The Skip button stops update checking for a week I think or maybe 6 hours - its hard to determine from the documentation - but the user doesn't know that (and doesn't know to click the Close icon to just ignore once) and it makes support difficult if a new version is needed but the user already pressed Skip.
How about having a split button with Skip Once/Skip for a Day/Skip for a Week (or whatever) so it is clear. Even better would be to let the choices be developer configurable.

**Comment by NikolaMilosavljevic** [comment]
This UI is displayed by ClickOnce runtime that is part of .NET FX. ClickOnce apps utilize .NET FX on user's machine for installing, launching and updating.

The following page describes ways to submit feedback and open issues with these products: https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019
