### ISSUE TITLE
dotnet-mage 6.0 requires 5.0

### ISSUE THREAD

**Issue by GH-Resforma** [dotnet/deployment-tools#170]
When using dotnet-mage in a Docker image from **mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019**. The command faults with:**The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.**

### Description

**C:\approot>dotnet tool install --global microsoft.dotnet.mage**
*You can invoke the tool using the following command: dotnet-mage*
*Tool 'microsoft.dotnet.mage' (version '6.0.0') was successfully installed.*

**C:\approot>dotnet-mage**
*It was not possible to find any compatible framework version*
*The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.*
 * - The following frameworks were found:*
      *6.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]*

### Configuration

**C:\approot>dotnet --version**
*6.0.100*

**C:\approot>dotnet tool list --global**
*Package Id* &emsp;&emsp;&emsp;&emsp;&emsp;             *Version*&emsp;      *Commands*
*---------------------------------------------------*
*microsoft.dotnet.mage* &emsp;     *6.0.0*  &emsp;      *dotnet-mage*

**C:\approot>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"**
*OS Name:                   Microsoft*
*OS Version:                10.0.17763 N/A Build 17763*

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic please fix and establish a proper model for future releases.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Please work with @rbhanda to establish publishing pipeline and incorporate versioning in the process.

**Comment by NikolaMilosavljevic** [comment]
Reopening - will close once new package gets released to nuget.org.

**Comment by NikolaMilosavljevic** [comment]
New version of Microsoft.DotNet.Mage, 6.0.1, has been released to nuget.org. It fixes this issue.

https://www.nuget.org/packages/Microsoft.DotNet.Mage/6.0.1

Installation command is the same:

`dotnet tool install --global microsoft.dotnet.mage`
