### ISSUE TITLE
Nuget package name should follow existing naming convention

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/deployment-tools#18]
Current: `Microsoft.Net.NetCoreCheck`

Expected: `Microsoft.NET.NETCoreCheck`

**Comment by NikolaMilosavljevic** [comment]
@MSLukeWest is this already in place?

**Comment by MSLukeWest** [comment]
> @MSLukeWest is this already in place?

No, I didn't make any change to address this

**Comment by MSLukeWest** [comment]
Fixed
