### ISSUE TITLE
Environment variable support in a .pubxml file

### ISSUE THREAD

**Issue by lovettchris** [dotnet/deployment-tools#180]
### Description

I need to hide the install location in my open source project, so I want to write this in my `ClickOnceProfile.pubxml` file:

```xml
<InstallUrl>$(ADA_KIOSK_STORAGE_URL)</InstallUrl>
```

but when I try this the profile editor comes up showing the correct thing, but every time I click "Publish" it rewrites this string with the actual variable, which I have to keep undoing in the git change.

### Configuration

C# WPF project in VS 2019:

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

```

### Regression?

Not sure

**Comment by lovettchris** [comment]
Never mind, it works now :-)

**Comment by NikolaMilosavljevic** [comment]
This is a feature of Visual Studio - best option to submit feedback is directly from VS: `Help` -> `Send Feedback` -> `Report a Problem` (or `Suggest a Feature`)
