### ISSUE TITLE
Assemblies in Vs.Redist.Common.NETCoreCheck packages do not have their symbols published anymore

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/deployment-tools#195]
### Description

Assemblies in Vs.Redist.Common.NETCoreCheck packages (All three architectures: x86|x64|arm64) do not have their symbols published anymore.

### Regression?

Yes, this regressed at some point between 5.0.0-rtm.20555.5 and 6.0.0-alpha.1.21071.2.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic please investigate.

**Comment by MSLukeWest** [comment]
Confirmed fixed in 7.0.0-preview.1.22263.1
