### ISSUE TITLE
Network share ClickOnce publish creates corrupt setup.exe

### ISSUE THREAD

**Issue by fuglede** [dotnet/deployment-tools#199]
This is a mirror of [this SO question](https://stackoverflow.com/q/71940968/5085211); figured posting it here would make it possible to get some eyes on it.

### Description
I have a .NET 5 application that I'm trying to use ClickOnce to publish. If I publish it locally (to, say, `bin\publish\`), everything is good, but if I use a network file share UNC path as the PublishDir, I end up with a corrupted `setup.exe`.

### Regression?
In the .NET Framework 4.7 version of the same application, this wasn't a problem, and publishing directly to network shares was possible.

### Other information
I've noticed that during publishing, `setup.exe` is some ~480 kB large while there's a small temporary file around as well, before `setup.exe` is ultimately replaced by the corrupt file. (The correct `setup.exe` would be around 658 kB).

**Comment by NikolaMilosavljevic** [comment]
@sujitnayak @John-Hart - is this a good place to track this issue?

**Comment by John-Hart** [comment]
@fuglede  can you please report this from within Visual Studio by going to the Help>Send Feedback>Report a Problem... menu?

**Comment by fuglede** [comment]
@John-Hart Done! FWIW, this happens regardless of whether I use the VS wizard or the msbuild command line tool.

**Comment by John-Hart** [comment]
@fuglede, thanks we see the feedback item and will contact you.

**Comment by NikolaMilosavljevic** [comment]
Closing in favor of VS Feedback item.
