### ISSUE TITLE
Click Once Add runtime(aspnetcore) not listed in existing perquisites

### ISSUE THREAD

**Issue by saivineeth100** [dotnet/deployment-tools#214]
I want to mention aspnetcore as dependency for clickonce , so that it downloads aspnetcore  before installing my app

my WPF app uses asp.net , so I need to install aspnetcore runtime before starting my app

I tried adding below xml to publish profile but didn't worked
```
    <BootstrapperPackage Include="Microsoft.NetCore.AspNetCoreRuntime.6.0.x64">
      <Install>True</Install>
      <ProductName>ASP .NET Core  Runtime 6.0.7 (x64)</ProductName>
    </BootstrapperPackage>
```

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by sujitnayak** [comment]
ClickOnce traditionally has not been used to publish aspnetcore apps. It only supports Forms, WPF and console app. We would need to triage this ask internally before commenting further.
Thanks.

**Comment by saivineeth100** [comment]
> ClickOnce traditionally has not been used to publish aspnetcore apps. It only supports Forms, WPF and console app. We would need to triage this ask internally before commenting further. Thanks.

This is for WPF app only , I want to add extra dependency as my wpf uses asp.net core to host web

**Comment by sujitnayak** [comment]
A feature request ticket has been created for this issue and can be tracked at:

https://developercommunity.visualstudio.com/t/ClickOnce-Add-runtimeaspnetcore-not/10330018

**Comment by sujitnayak** [comment]
We recommend that you follow the steps mentioned in this article to create your own bootstrapper package for aspnetcore:

https://learn.microsoft.com/en-us/visualstudio/deployment/creating-bootstrapper-packages?view=vs-2022

Thanks.

**Comment by sujitnayak** [comment]
@NikolaMilosavljevic could you please close out this issue.
