### ISSUE TITLE
Clickonce - combine selfcontained deployments with on-demand dependencies

### ISSUE THREAD

**Issue by statler** [dotnet/deployment-tools#271]
It is possible to mark libraries to be downloaded on demand. It is also possible to create a self contained deployment that includes the .Net runtime.

It would be great if it was easily configurable to have a selfcontained package that only pulled the additional libraries if they aren't available on the client's machine. This would provide a much improved experience.

**Comment by NikolaMilosavljevic** [comment]
@statler can you provide some more details about this scenario? Which experience would align with ClickOnce deployment?

**Comment by NikolaMilosavljevic** [comment]
[Triage] We are not planning this feature at the moment.
