### ISSUE TITLE
RFC 3161 timestamp uses SHA-1 when publisher signing certificate uses SHA-384

### ISSUE THREAD

**Issue by dtivel** [dotnet/deployment-tools#275]
### Description

1. Extract the contents of [WindowsFormsApp1.zip](https://github.com/dotnet/deployment-tools/files/11466502/WindowsFormsApp1.zip) to your local drive (e.g.:  `C:\repro\WindowsFormsApp1`).  (I created this C# Windows Forms App (.NET Framework) project in Visual Studio 2022, published it, deleted some files unnecessary to the repro, and ZIP-ed it up.)
2. Save [this PowerShell script](https://gist.github.com/dtivel/731d9ec4654cb97a9762abd44e801e90) in a directory (e.g.:  `C:\repro\repro.ps1`).
3. Where `<DirectoryPath>` is the root directory for the extracted content, open a PowerShell prompt, path to the PowerShell script created in the previous step, and execute:

   ```PowerShell
   .\repro.ps1 '<DirectoryPath>\publish'
   ```

   Example:

   ```PowerShell
   .\repro.ps1 'C:\repro\WindowsFormsApp1\publish'
   ```

This will sign the application manifest using 2 certificates with different signature algorithms:  RSA SHA-256 and RSA SHA-384.  Then, the timestamp signed CMS will be extracted to .p7s files.  Comparing the two signed CMS's, you'll see that the RFC 3161 timestamp message imprint for the SHA-256 RSA certificate uses SHA-256, while the message imprint for the SHA-384 RSA certificate uses SHA-1.

This bug appears to have been fixed years ago via https://github.com/dotnet/msbuild/pull/6882; however, `dotnet-mage` isn't using the fix.

### Configuration

<details><summary>dotnet --info</summary>

```
.NET SDK:
 Version:   7.0.400-preview.23225.8
 Commit:    c63317749e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  7.0.105 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23225.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-alpha1.19530.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha1.19528.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-alpha1.19530.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

<details><summary>dotnet tool list --global</summary>

```
Package Id                 Version                 Commands
--------------------------------------------------------------------
microsoft.dotnet.mage      7.0.0                   dotnet-mage
```
</details>

### Regression?

No

### Other information

This is related to https://github.com/dotnet/msbuild/issues/6732, but that bug was fixed years ago.

This behavior also reproduces with .NET Framework's mage.exe.

CC @NikolaMilosavljevic, @clairernovotny

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic please investigate.
