### ISSUE TITLE
NETSDK1195 error building repo using .NET 8 RC1 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/deployment-tools#288]
The following error occurs when building this repo using a recent build of .NET 8 RC1 SDK (8.0.100-rc.1.23410.12):

```
/vmr/.dotnet/sdk/8.0.100-rc.1.23410.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1195: IsTrimmable is not supported for the target framework. Consider multi-targeting to a supported framework to enable trimming, and set IsTrimmable only for the supported frameworks. For example:
<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
For more information, see https://aka.ms/netsdk1195 [/vmr/src/deployment-tools/artifacts/source-build/self/src/Build.proj]
```

I believe this error originates from the changes in https://github.com/dotnet/sdk/pull/34429. The build is configured to use `TargetFramework=net472` which doesn't have trimming support. The fact that `net472` is being targeted also seems problematic in the context of source-build.

**Comment by MichaelSimons** [comment]
cc @joeloff

**Comment by joeloff** [comment]
@mthalman what is targeting 472? I don't see anything in the deployment-tools when I searched under src. Is this happening when building deployment-tools from the VMR?

**Comment by mthalman** [comment]
You can look at any source-build run of deployment-tools and see `net472` all over the place in MSBuild. Here's a [binlog](https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzM3NzU0NC9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PZmZsaW5lX01zZnRTZGtfeDY0X0J1aWxkTG9nc19BdHRlbXB0MQ2/content?format=file&subPath=%2Fsrc%2Fdeployment-tools%2Fartifacts%2FbuildLogs%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog) from a recent build.
