### ISSUE TITLE
Azure Trusted Signing support

### ISSUE THREAD

**Issue by rogerfar** [dotnet/deployment-tools#362]
Hello,

We're investigating using (https://azure.microsoft.com/en-us/products/trusted-signing)[Azure Trusted Signing], which is very promising as it avoid messing with physical USB keys and is very reasonably priced.

Is there a plan to support this natively in Mage.exe?

**Comment by John-Hart** [comment]
Currently we do not have any plans to support this in the MSBuild manifest tasks.  

You might want to look at using https://github.com/dotnet/sign

**Comment by NikolaMilosavljevic** [comment]
Closing as this is not planned.
