### ISSUE TITLE
[internal/main] Native NetCoreCheck projects are failing to build

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/deployment-tools#398]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2565691&view=results

```
LINK : fatal error C1047: The object or library file 'D:\a\_work\1\s\.dotnet\packs\Microsoft.NETCore.App.Host.win-x64\9.0.0-rc.2.24473.5\runtimes\win-x64\native\libnethost.lib' was created by a different version of the compiler than other objects like 'NETCoreCheckCA.dir\Release\MsiLogger.obj'; rebuild all objects and libraries with the same compiler [D:\a\_work\1\s\artifacts\obj\win-x64.Release\native\projects\NetCoreCheck\CA\NETCoreCheckCA.vcxproj] 
LINK : fatal error LNK1257: code generation failed [D:\a\_work\1\s\artifacts\obj\win-x64.Release\native\projects\NetCoreCheck\CA\NETCoreCheckCA.vcxproj] 
```

This only shows in internal AzDO builds, and not on GitHub, likely due to different build pools being used. It first appeared with Arcade update: https://github.com/dotnet/deployment-tools/pull/392

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic should this issue be re-opened to track re-enabling the native projects?

**Comment by NikolaMilosavljevic** [comment]
> [@NikolaMilosavljevic](https://github.com/NikolaMilosavljevic) should this issue be re-opened to track re-enabling the native projects?

We did re-enable them with https://github.com/dotnet/deployment-tools/pull/406

**Comment by ViktorHofer** [comment]
Oh I see. I was confused because the comment is still there: https://github.com/dotnet/deployment-tools/blob/19a31be752b4a46599dfb75ee2130aa1f8824456/Build.proj#L7

**Comment by NikolaMilosavljevic** [comment]
> Oh I see. I was confused because the comment is still there:
> 
> [deployment-tools/Build.proj](https://github.com/dotnet/deployment-tools/blob/19a31be752b4a46599dfb75ee2130aa1f8824456/Build.proj#L7)
> 
> Line 7 in [19a31be](/dotnet/deployment-tools/commit/19a31be752b4a46599dfb75ee2130aa1f8824456)
> 
>  

Yeah, that should be fixed - I'll update the comment or remove it.
