### ISSUE TITLE
[loc][query] Assistance with translations

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/deployment-tools#43]
Does it refer to Microsoft Launcher (due to capitals) or is it a generic term and, therefore, translatable? Left in English by now, please confirm. Several occurrences, examples: Launcher successfully added. 0; "LauncherSuccessfullyAdded" Launcher template "{0}" does not exist. 0; "MissingLauncherTemplate"

**Comment by cristianosuzuki77** [comment]
vcq 322030

**Comment by NikolaMilosavljevic** [comment]
@cristianosuzuki77 Launcher is the name of the binary and also the primary concept for ClickOnce activation of .NET 5 apps. It is true that Launcher binary 'launches' the .NET 5 application.

When we say 'Launcher successfully added' it refers to the binary, which is named Launcher.exe. Similarly, in the next example 'Launcher template {0} does not exist' - we refer to the binary name.
