### ISSUE TITLE
Add support for URL parameters

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/deployment-tools#53]
It would be valuable if .NET 5 applications, deployed by ClickOnce, could gain access to URL parameters, specified by the user in the app activation URL.

.NET FX applications could use `ApplicationDeployment` class to obtain URL parameters: https://docs.microsoft.com/en-us/dotnet/api/system.deployment.application.applicationdeployment.activationuri?view=netframework-4.8

This method is not available to .NET 5 applications as `ApplicationDeployment` class does not exist.

However, Launcher is a .NET FX application and has access to `ActivationUri` property.

One solution is for Launcher to obtain URL parameters and persist them to a Json file that would be read by .NET 5 application. This would follow the proposed solution for the similar issue: https://github.com/dotnet/deployment-tools/issues/27

**Comment by billpeet** [comment]
Any update on this one?
As far as I can see there's literally no way of passing command line arguments to a ClickOnce-deployed .NET 5.0 app at the moment, correct me if I'm wrong?
This is a show-stopper for me porting existing Framework apps to .NET 5.0.

**Comment by NikolaMilosavljevic** [comment]
> Any update on this one?
> As far as I can see there's literally no way of passing command line arguments to a ClickOnce-deployed .NET 5.0 app at the moment, correct me if I'm wrong?
> This is a show-stopper for me porting existing Framework apps to .NET 5.0.

Thank you for your interest in this feature. This is still being tracked for 6.0 milestone. However, we do not have any specific timeline yet.

**Comment by tormnator** [comment]
This also a major issue for us. We deploy our application to hundeds of customers via ClickOnce, but can't move to .NET 5/6 until we have support for URL parameters (as well as some of the missing pieces of System.ApplicationDeployment). By "6.0 milestone", do mean literally by 6.0? Or sometime after the initial 6.0 release?

**Comment by luronumen** [comment]
Unable to port WinForms project from **.NET Framework 4.8** to **.NET 5.0** due to the following issue:
_CS0234 - The type or namespace name 'Deployment' does not exist in the namespace 'System' (are you missing an assembly reference?)_

**Comment by Pipelynx** [comment]
I just wanted to add that I also need this, please add it in a future version!

**Comment by NikolaMilosavljevic** [comment]
> Parameters must also work on offline intallations (passing them as arguments to the .appref-ms, shortcut in the users start menu).

Thank you for your interest in this feature. I've added the "untriaged" label to bring this to our next triage meeting.

**Comment by MichaelSimons** [comment]
[Triage] This is a feature request that we should consider for 7.0

**Comment by luronumen** [comment]
> [Triage] This is a feature request that we should consider for 7.0

Only for .NET 7.0 @MichaelSimons? I thought that .NET 6.0 (LTS) would come with this fix. :(

**Comment by billpeet** [comment]
Seriously??? So we're not likely to see this until the end of 2022.
We're literally talking about the ability to pass command line parameters to an app, pretty basic stuff. A major oversight for initial release, let alone something that's going to take 2 years to fix (.NET 5.0 to 7.0)
Any chance this could be brought forward at all?

**Comment by DanLBarr** [comment]
We need the ApplicationDeployment.IsNetworkDeployed and ApplicationDeployment.CurrentDeployment.ActivationUri APIs or something equivalent to complete our port to .NET 6. We currently provide our customers a way to license their ClickOnce application (using our library) locked to their URI using these APIs with the .NET Framework.

**Comment by Mehran-S** [comment]
We really need the ApplicationDeployment.IsNetworkDeployed and ApplicationDeployment.CurrentDeployment.ActivationUri APIs for .Net 6.

**Comment by NC-GNVFL** [comment]
We also need this before we can move forward with .NET6.  ApplicationDeployment.IsNetworkDeployed and ApplicationDeployment.CurrentDeployment.ActivationUri APIs are required for us.

**Comment by NikolaosWakem** [comment]
We need ApplicationDeployment.CurrentDeployment.ActivationUri today for a new 5.0 app 

There must be some kind of workaround?
Maybe a call to the OS?
Some magic reflections hack?
A hint in the right direction would be helpful please and maybe I can figure something out?

**Comment by billpeet** [comment]
@NikolaosWakem my workaround was to browse the AppData folder to find the installed offline .exe file, then launch the exe file directly with arguments (instead of launching the ClickOnce app with URL arguments).

Something like this:

```c#

public static void RunClickOnceAppWithArgs(string appName, params string[] args)
{
	var exePath = FindClickOnceApp(appName);
	Process.Start(exePath, string.Join(" ", args));
}

private static string? FindClickOnceApp(string appName)
{
	var appsDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Apps", "2.0");
	if (!Directory.Exists(appsDir))
		return null;
	var obvDir = Directory.EnumerateDirectories(appsDir).FirstOrDefault(d => d != "Data");
	if (obvDir is null)
		return null;
	obvDir = Directory.EnumerateDirectories(appsDir).FirstOrDefault();
	if (obvDir is null)
		return null;
	var appPrefix = appName.ToLower().Substring(0, 4);
	var appDirs = Directory.EnumerateDirectories(obvDir, appPrefix + "*");
	foreach (var dir in appDirs.OrderByDescending(d => new DirectoryInfo(d).LastWriteTimeUtc))
	{
		var exePath = Path.Combine(dir, appName + ".exe");
		if (File.Exists(exePath))
			return exePath;
	}
	return null;
}

```

One limitation of this is that it bypasses ClickOnce functions like automatic updates, since it just launches the app directly.
To get around that I've used @derskythe's solution https://github.com/derskythe/WpfSettings to implement an update check within the app itself.

**Comment by sloutsky** [comment]
[MS Kusto team]
Our team develops Kusto.Explorer application (using ClickOnce) and relies heavily on ClickOnce ability to provide information about deployment URI and Query (arguments) for the following scenarios:
- Deep-linking to a specific Kusto cluster + running a query 
- Understanding application feature set based on Deployment URI 

Not having these two scenarios are currently blocking our ability to migrate fully to .NET Core.

**Comment by e-master** [comment]
I didn't realize support for this feature has been pushed to .net 7 - i was actually waiting for .net 6 to finally be able to upgrade our app from net452. This is really a showstopper. 

However, i think this issue is relatively easy to solve. I've submitted a PR (#135) that addresses my immediate problem (passing through command line arguments - the `AppDomain.CurrentDomain.SetupInformation.ActivationArguments?.ActivationData` array). I pass that array to my app as process scoped environment variables (e.g.: `CLICKONCE_ACTIVATIONDATA_1`, `CLICKONCE_ACTIVATIONDATA_2`, etc.). Fingers crossed MS will accept my PR, because this is extremely important for me. I believe this same approach (process scoped env variables) could be used for the parameters in this issue also (`ActivationUri`, etc.).

**Comment by Mirage006** [comment]
How is this issue progressing? It's still tagged with milestone 6; will this still be added to the NET 6 release of this year. From the comments I gather support has been pushed, but at the same time seems fairly trivial to include, see @e-master ?

Like many others here, it is pivotal in our decisionmaking regarding the move from full framework.

**Comment by Lumoryel** [comment]
So, it's 2022 and I guess there is still no solution for using ApplicationDeployment in .NET 6?

**Comment by billpeet** [comment]
@NikolaMilosavljevic is this on track for .NET 7?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic is this on track for .NET 7?

Yes, it is - in fact this feature is being tested right now, and will be available in a preview soon.

**Comment by ExactImage** [comment]
Can't believe we just went through all the pain of updating a more than 1 million line project to .net 6 only to stumble at the final hurdle of getting the version from the runtime.  This is painful to say the least.

**Comment by NikolaMilosavljevic** [comment]
PR created: https://github.com/dotnet/deployment-tools/pull/208

Feedback is welcome!

**Comment by NikolaMilosavljevic** [comment]
Shipped with Preview 2: https://github.com/dotnet/deployment-tools/discussions/212

**Comment by davidroth** [comment]
@NikolaMilosavljevic Does this also work when publishing via a click once publish profile in Visual Studio?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic What are the required stops to make this work when publishing via a click once publish profile in Visual Studio?
> 
> It seems not to work. Installed latest VS 2022 preview and .NET 7 RC. Published ClickOnce via VisualStudio. When starting the ClickOnce App via the Browser, the environment variable `ClickOnce_ActivationUri` is not available.

I believe this has first shipped with Visual Studio 17.3. There is a checkbox in ClickOnce publishing profile settings that needs to be checked for this to work. @sujitnayak , @John-Hart can you help @davidroth get this working in Visual Studio?

**Comment by John-Hart** [comment]
If you're using VS 2022 version 17.3 or later, you should see the option "Allow URL parameters to be passed to application" on the Publish Options dialog.  If you check that option the property TrustUrlParameters will be set to True, in the pubxml file.

**Comment by davidroth** [comment]
@NikolaMilosavljevic @John-Hart 

Thanks, that did the trick!

**Comment by Nils-Berghs** [comment]
@NikolaMilosavljevic @John-Hart ,  I have the option in VS 2022 to "Allow URL parameters to be passed" on a .Net 6 application but it doesn't work there:

I presume these are two seperate errors:
- It does not work on .net 6
- The UI shows an option that will not work

But even besides that, clickonce is not a viable option for application development as pinning an app to the taskbar disables the auto update feature, which is what clickonce was all about.

Anybody who knows a viable, alternative? (I can't wait until .net 13 when clickonce may or may not work as good as it did in 4.x)

**Comment by davidroth** [comment]
> I presume these are two seperate errors:
> 
> It does not work on .net 6
> The UI shows an option that will not work

@Nils-Berghs I tested it on .net 6 and it works as expected. I guess you'd have to clarify what exactly is not working on your side and how you tested it.

**Comment by Nils-Berghs** [comment]
@davidroth, I was just editing my message as I also tried on .net 7 and I have the same exact result.

If I start my app from the command line, using the appref-ms shortcut whitout parameters It works fine, the update check is performed and the application is started.

If I pass a parameter from the command line the update (so I gues the launcher) starts and even updates if one is available but the app itself is not started at all, it just silently fails: 

 `C:\Users\Nils\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\...> .\myapp.appref-ms' -myparam`

Do I have to specify the parameters in a specific format.

As for the other issue: I guess that due to the launcher being a different program that there will never be a solution for pinning apps to the taskbar.

**Comment by davidroth** [comment]
@Nils-Berghs I only tried passing the parameters to the click once web url. And that worked as expected inkl. auto update and starting. (This is how we used it in the .NET Framework days ...)

Example:
`http://david.local:5224/ClickOnceTest.application?SomeArgument=value&Arg2=value2....`
(david.local is just a local web server in this example for testing purposes ...)

I have never directly invoked the "appref-ms" with args before, so I dunno whats wrong in your scenario.

**Comment by Nils-Berghs** [comment]
@davidroth I quickly tried but I haven't gotten far, as I have never publish to a webserver before. If I do this I get the publish page and I'm able to install the app and launch it from start. 
But the .application file simply opens as xml in both chrome and edge (which makes total sence to me). I thought that this publishing to a website was a 'Internet Exploder' kind of thing. 

I'm guessing I'll need to install some add-on to bypass security... (and that to pass parameters to an application that is already installed locally..... as its friday I'd like some of that drink they had while designing clickonce for .net5.0 ;-)    )

**Comment by NikolaMilosavljevic** [comment]
> I'm guessing I'll need to install some add-on to bypass security... (and that to pass parameters to an application that is already installed locally..... as its friday I'd like some of that drink they had while designing clickonce for .net5.0 ;-) )

ClickOnce activation is supported in Edge - you might have it disabled. Here's the relevant page that discusses the design with directions: https://learn.microsoft.com/en-us/deployedge/edge-learn-more-co-di

ClickOnce activation on Chrome requires a third-party plug-in or extension - there are several, but I do not have a recommendation.

Update from Taskbar-pinned app works, if app is pinned from the Start Menu - right-click on app and select "Pin to taskbar". This is a temporary workaround; the solution is being planned for near future, see latest comments in this issue: https://github.com/dotnet/deployment-tools/issues/74

**Comment by Nils-Berghs** [comment]
> ClickOnce activation is supported in Edge - you might have it disabled. Here's the relevant page that discusses the design with directions: https://learn.microsoft.com/en-us/deployedge/edge-learn-more-co-di
> 
> ClickOnce activation on Chrome requires a third-party plug-in or extension - there are several, but I do not have a recommendation.

What about Firefox, Opera, ... everybody (except some Microsoft executives) knows that you cannot force a browser on users.

So back to the main question, when/how will clickonce parameters be available for the appref-ms?

**Comment by NikolaMilosavljevic** [comment]
> What about Firefox, Opera, ... everybody (except some Microsoft executives) knows that you cannot force a browser on users.

Plug-ins have been available for other browsers for many years. Microsoft can only enable ClickOnce support for Microsoft-built browsers, but developers are free to deploy solutions, i.e. plug-ins, to Chrome, Firefox and any other browser they wish. This is not specific to ClickOnce on .NET (Core).

> So back to the main question, when/how will clickonce parameters be available for the appref-ms?

URL parameters support have been available since June of this year, in dotnet-mage preview and in Visual Studio 17.3. This adds support that was present in .NET FX but missing from ClickOnce for .NET. More on this at: https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-retrieve-query-string-information-in-an-online-clickonce-application?view=vs-2022&tabs=csharp

Important note is that these are "URL parameters", not parameters for appref-ms. But you could still use the same model to pass the parameters, like in the article shared above, by specifying parameters for your .application file.

**Comment by Nils-Berghs** [comment]
> Important note is that these are "URL parameters", not parameters for appref-ms. But you could still use the same model to pass the parameters, like in the article shared above, by specifying parameters for your .application file.

We have some applications that are desktop applications because they must work at all times (even if network connection is temporarily broken, they must store data locally and send to the server when connection is restored), so again  when/how will clickonce parameters be available for the appref-ms?

In the mean time we are moving to Squirrel for current developments, it's like clickonce but it works....

**Comment by NikolaMilosavljevic** [comment]
> > Important note is that these are "URL parameters", not parameters for appref-ms. But you could still use the same model to pass the parameters, like in the article shared above, by specifying parameters for your .application file.
> 
> We have some applications that are desktop applications because they must work at all times (even if network connection is temporarily broken, they must store data locally and send to the server when connection is restored), so again when/how will clickonce parameters be available for the appref-ms?
> 
> In the mean time we are moving to Squirrel for current developments, it's like clickonce but it works....

While it was possible to specify parameters/arguments for appref-ms and consume them from the launched .NET FX application, the recommended model would have been to store them in application's config file. I presume that your scenarios are not fully covered by that solution.

I have created the issue: https://github.com/dotnet/deployment-tools/issues/236 The fix should be easy, and while the appref-ms usage will stay the same, application will be able to obtain those arguments, but in a slightly different way.
