### ISSUE TITLE
ClickOnce publish fails if project reference uses different target framework

### ISSUE THREAD

**Issue by billpeet** [dotnet/deployment-tools#71]
Not sure if this is the right repo to file this under, but here goes.

Repro steps:
1. Create Windows desktop app, targeting net5.0-windows (or netcoreapp3.1)
1. Create a project reference to a class library, targeting netstandard2.1 (or netstandard2.0)
1. Deploy using ClickOnce, using target framework net5.0-windows, Framework-dependent, Portable

Publish fails, with following build output:
```
2>Metadata file 'D:\Documents\DeploymentTester\SomeClassLibrary\bin\Release\net5.0-windows\ref\SomeClassLibrary.dll' could not be found
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

If I delete the project reference, or change project reference to target net5.0-windows, publish works fine.
This makes the new ClickOnce unusable for me at the moment, as I have a number of apps with shared libraries that I am attempting to port one at a time, so need to be able to use netstandard2.0 libraries to be compatible with my Framework apps.

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by John-Hart** [comment]
Thanks @billpeet 

I've opened a Visual Studio feedback item to track this: https://developercommunity2.visualstudio.com/t/ClickOnce-Publish-for-NET-Core-31-and-/1275937. I did find a work around was to target a specific runtime instead of using Portable. 

If you find run into any more issues please use the Help >Send Feedback menu in Visual Studio

**Comment by NikolaMilosavljevic** [comment]
Closing in favor of VS Feedback issue.
