### ISSUE TITLE
.NET 5 ApplicationDeployment.CurrentDeployment.DataDirectory

### ISSUE THREAD

**Issue by rallets** [dotnet/deployment-tools#72]
Hi, I have an application that rely on `ApplicationDeployment.CurrentDeployment.DataDirectory` and `ApplicationDeployment.IsNetworkDeployed` to be able to get access to a json config file that should be kept between different versions of the same application. 
I know `System.Deployment.Application` is not supported now.
So I'm wondering how I can achieve the same functionality in .NET 5, what is the new strategy with the new tool?

**Comment by NikolaMilosavljevic** [comment]
Related to https://github.com/dotnet/deployment-tools/issues/27

**Comment by NikolaMilosavljevic** [comment]
Thanks for adding another voice for improving ApplicationDeployment API availability in ClickOnce for .NET 5. We are tracking this request in the following issue: #27
