### ISSUE TITLE
ApplicationDeployment should be migrated to NET 5.0

### ISSUE THREAD

**Issue by luisabreu** [dotnet/deployment-tools#79]
Hello guys.

It seems like ApplicationDeployment API [won't be ported to .NET 5.0](https://github.com/dotnet/deployment-tools/issues/9). This API is really important for a couple of important scenarios:

1. it gave us a way to force the user to always use the latest version of the windows forms app
2. it allowed us to easily implement an auto-update procedure for long lived apps (similar to what spotify does)

Without this API, we can no longer implement these scenarios which are crucial for our windows forms apps (installed through clickonce). 

I'd like to know if there are any plans to bring the ApplicationDeployment API to .NET 5.0 in future versions or should we simply keep  our windows apps forever in .NET 4.8 until it can no longer run in future OS versions.

Thanks.

**Comment by NikolaMilosavljevic** [comment]
Thanks for adding another voice for improving ApplicationDeployment API availability in ClickOnce for .NET 5. We are tracking this request in the following issue: https://github.com/dotnet/deployment-tools/issues/27

**Comment by jonrmorgan99** [comment]
Hi All,

My first contribution to GitHub !

I've just migrated my 20 year old app (originally written in 8086Assembler) from .Net 4.6.1 to .Net 5. It was great to find that ClickOnce made the cut and the new wizard is impressive. 

However like the OP, without in-app updating using the ApplicationDeployment API I'll have to stay with .Net 4.8 or look at alternatives to ClickOnce. 

Over the years ClickOnce has proven very reliable - "fix and forget" - so why not make it even better for Net 5 !

Thanks

**Comment by DDD25583** [comment]
I just tried to migrate a net4.8 app to .NET 6 when I came across this issue.
Being able to get the CurrentVersion is crucial in are error and bug-processing procedures.
As the production environment contains a lot of computers, updating (close and restart) an app is done once in the 24 hours.
So it is important that we know on which version of the app, an error is thrown.

**Comment by jonrmorgan99** [comment]
A year on and still no sign of the ClickOnce ApplicationDeployment API returning.

Please could we have a progress update ? Will it be restored in Net7 ?

The long silence on this topic makes it difficult to plan migration from NetFx 4.8. 
If CO is not going to be supported then better to know now so we can switch to an alternative installer.

**Comment by NormanGiHu** [comment]
Ticket closed? Any plans to solve the issue in .net 7 ? Or is there an alternative for switching off updates via the the app settings and not only via the clickonce configuration?
