### ISSUE TITLE
Bug: ClickOnce publish error when solution contains projects with different targets

### ISSUE THREAD

**Issue by konradsikorski** [dotnet/deployment-tools#80]
I have WPF application. I have migrated it to .NET 5 and it works, great. My app uses ClickOnce to release new versions. The ClickOnce publish process will fail when the solution contains projects with different target frameworks.

To simplify the problem please create one empty WPF application in .NET 5 (target framework: net5.0-windows) next add library project to this solution in .NET 5 (target framework: net5.0). Now try to publish the project. You will receive an error like this:

> 2>------ Publish started: Project: WpfApp123-net5, Configuration: Release Any CPU ------
> 2>It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Pro Preview\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:5 /define:TRACE;RELEASE;NET;NET5_0;NETCOREAPP;WINDOWS /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0\ref\net5.0\Accessibility.dll" /reference:...
> 2>Metadata file 'C:\...\source\repos\WpfApp123-net5\ClassLibrary1\bin\Release\net5.0-windows\ClassLibrary1.dll' **could not be found**

The "ClassLibrary1.ddl" is not in "net50-windows" folder instead it is in "net5.0" folder.

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by John-Hart** [comment]
@konradsikorski thanks.  We're working on a solution.  You can track the status with this Developer Community issue: https://developercommunity2.visualstudio.com/t/ClickOnce-Publish-for-NET-Core-31-and-/1275937.

If you run into further ClickOnce issues in Visual Studio you can report them via the Help > Send Feedback menu.

Thanks
John
