### ISSUE TITLE
Publishing to Unc path with ClickOnce causes VS to hang

### ISSUE THREAD

**Issue by desjarlais** [dotnet/deployment-tools#83]
I typically deploy to an internal unc share for my app, but recently the server I use was down and I didn't know it.  When I went to publish my updated project to the share, VS2019 would hang and never respond back, it just kept the spinning icon.  Shouldn't there be some kind of timeout for unavailable / unreachable unc paths?

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by John-Hart** [comment]
@desjarlais that's not a bad idea, it is just a MSBuild that cannot access the path at that point.  We'll keep an eye on this and if this become common we'll look adding some check. 
If you have other suggestions for the Visual Studio ClickOnce please use the Help > Provide Feedback menu

**Comment by desjarlais** [comment]
Will do, thanks for the tip!
