### ISSUE TITLE
Error: assembly specified in the application dependencies not found

### ISSUE THREAD

**Issue by desjarlais** [dotnet/deployment-tools#86]
I added WebView2 to my project and deployed through ClickOnce.  After installing, I get the following error in Event Viewer:

Description: A .NET application failed.
Application: Case NotePad.exe
Path: C:\Users\brandes\AppData\Local\Apps\2.0\2V7CXATV.M61\CX319N6T.2CJ\case..tion_5964a32ae0c4e4e8_0001.0000_70afaffa3727f90c\Case NotePad.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Case NotePad.deps.json) was not found:
    package: 'Microsoft.Web.WebView2', version: '1.0.664.37'
    path: 'runtimes/win-x64/native/WebView2Loader.dll'

I took a procmon of the launch and it looks like this is the problem:

6:06:25.3103630 PM	Case NotePad.exe	24596	CreateFile	C:\Users\brandes\AppData\Local\Apps\2.0\2V7CXATV.M61\CX319N6T.2CJ\case..tion_5964a32ae0c4e4e8_0001.0000_71adcf692eb7ed4c\runtimes\win-x64\native\WebView2Loader.dll	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a	"C:\Users\brandes\AppData\Local\Apps\2.0\2V7CXATV.M61\CX319N6T.2CJ\case..tion_5964a32ae0c4e4e8_0001.0000_71adcf692eb7ed4c\Case NotePad.exe"

The path is not created and if I create the following path by adding the folders "\runtimes\win-x64\native\":

C:\Users\brandes\AppData\Local\Apps\2.0\2V7CXATV.M61\CX319N6T.2CJ\case..tion_5964a32ae0c4e4e8_0001.0000_71adcf692eb7ed4c\runtimes\win-x64\native\

Then add WebView2Loader.dll, I no longer repro the app failing to launch.  Is this expected?

**Comment by NikolaMilosavljevic** [comment]
@John-Hart @sujitnayak can you please route this into VS ClickOnce issue and let us know so we can close this issue?

**Comment by desjarlais** [comment]
I remember reading this was fixed in 16.8.4, but I did install that and still noticed the issue.  

For some reason, now it seems to be working fine, so I don't know if the publish profile I was using had some kind of cached data that caused this issue to continue to repro, but after deleting my previous profile and re-publishing, now the runtimes location appears to be getting added correctly and the issue no longer reproduces.

**Comment by John-Hart** [comment]
@desjarlais I'm glad to hear it is working for you now.  The fix was in MSbuild so not sure why it didn't work the first time after 16.8.4 was installed.
