### ISSUE TITLE
Mage with EV Cert on usb Stick

### ISSUE THREAD

**Issue by wegoodwin** [dotnet/deployment-tools#97]
Hi,

EV Certs are now given out on a usb stick.  I need to make a change to the manifest file for a Clickonce deployment, but mage does not give the option of using the usb stick it only takes .pfx files.  Is there some sort of flag I am unware of that will let me resign an app with mage?

**Comment by NikolaMilosavljevic** [comment]
@wegoodwin is this for dotnet-mage and .NET 5 or .NET FX 4.8?

**Comment by wegoodwin** [comment]
@NikolaMilosavljevic 

I figured out what I needed to do.  The -CertHash parameter can be used in lieu of certfile/password.  The certhash value is the same thing as the thumbprint which you can find on the certificate properties.  

For example:
mage -Sign AppToDeploy.exe.manifest -CertHash 1a2222b3d444444c5555d666666b77eee888ff99g
